### ISSUE TITLE
Allow updating multiple records at once

### ISSUE THREAD

**Issue by Enduriel** [fernvenue/cloudflare-ddns#2]
Would be great to have a `CLOUDFLARE_RECORD_NAMES` var (or allow doing this in the current `CLOUDFLARE_RECORD_NAME` var) where you could pass a comma separate list of records to update. For example `*.example.com,@.example.com`

**Comment by fernvenue** [comment]
Unfortunately, Cloudflare use completely different ID for each record, even if they are in one zone or same type. And yea, maybe we can do something about multiple records support :)

**Comment by fernvenue** [comment]
Supported in https://github.com/fernvenue/cloudflare-ddns/commit/3fcb6f3799c0b06d01a0feb1ff156384a0997d1e, and I'm gonna close this issue for now.
